
name: Create Release Archive

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Kodi addon zip
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          git archive --format=zip  --prefix=movary-kodi-addon/ --output=movary-kodi-addon-${VERSION}.zip HEAD

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./movary-kodi-addon-${{ github.ref_name }}.zip
          asset_name: movary-kodi-addon-${{ github.ref_name }}.zip
          asset_content_type: application/zip

